### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by takayak** [takayak/chat-space#9]
# IPアドレス
52.69.141.149

**Comment by miyu-yamamoto** [comment]
小山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ サイドバーのグループ名の下に線が表示される**
[![Image from Gyazo](https://i.gyazo.com/59007ed049b05e94a5f119e6ea5feed3.png)](https://gyazo.com/59007ed049b05e94a5f119e6ea5feed3)

**○ 縮小表示するとファイルを選択するアイコンの位置がずれる**
[![Image from Gyazo](https://i.gyazo.com/fdf26eee95dd1a9b100a4eb0bb9501e9.gif)](https://gyazo.com/fdf26eee95dd1a9b100a4eb0bb9501e9)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
